### ISSUE TITLE
Does this help to get the token from email and password

### ISSUE THREAD

**Issue by shifoc** [3052/google#43]
https://github.com/whyorean/AASTokenGrabber/blob/master/main.py

**Comment by 3052** [comment]
the code there is highly misleading.

the code above is an implementation of Android 4.4 (2013). since Android 5 (2014) google uses bot-guard via JavaScript. the older implementation does allow email/password login, but it also is protected by TLS fingerprinting. the python TLS at the time just randomly worked, but later versions of python TLS dont, which is why you get these errors:

https://github.com/whyorean/AASTokenGrabber/issues/1
https://github.com/whyorean/AASTokenGrabber/issues/5

because unless you use the exact correct TLS stack, the request gets rejected, even if the payload otherwise is perfect. other implementation specify the TLS stack, so are better option:

https://github.com/simon-weber/gpsoauth

but regardless, its still 11 year old version, so I dont want to support it anymore. another option might be webview:

https://github.com/zzl/go-webview2/issues/1
